#!/usr/bin/env python3
"""Fallback GitHub write-helper for posting a comment and merging a PR with a
write-time mergeable_state re-check. The github-mcp now has native tools for both
(`github_comments` and `github_merge_pull_request`); this helper is retained for two
cases: a deployed github-mcp that predates `github_comments`, and callers that want
the atomic re-verify-mergeable-then-comment-then-merge in one guarded step. (Closing
is done via the MCP — `github_issues action=update` / `github_pulls action=update`
with state=closed — so this helper deliberately does not implement close.)

Auth: reads the token from the ``GITHUB_TOKEN`` runtime environment variable.
No token is ever printed or read from a plaintext credential file.

SAFETY: both subcommands DRY-RUN by default and print what they would do. Nothing
is sent unless `--confirm` is passed. `merge` additionally refuses unless the
caller has already classified the PR safe_merge (the skill's job).

Usage:
  python gh_write.py comment <owner/repo> <number> --body "..." [--confirm]
  python gh_write.py merge   <owner/repo> <pr_number> [--method squash|merge|rebase] [--confirm]

Always prefix triage comments with the AI disclaimer (the skill enforces this):
  > *This was generated by AI during triage.*
"""

from __future__ import annotations

import argparse
import os
import re
import sys

from github_agent.github_http import github_json_request

REPOSITORY_RE = re.compile(r"^[A-Za-z0-9_.-]{1,100}/[A-Za-z0-9_.-]{1,100}$")


def _token() -> str:
    tok = os.environ.get("GITHUB_TOKEN")
    if tok:
        return tok
    sys.exit("No GitHub token is configured.")


def _api(method: str, path: str, payload: dict | None) -> tuple[int, dict]:
    try:
        return github_json_request(method, path, _token(), payload)
    except RuntimeError:
        return 503, {"error": "GitHub request failed"}


def cmd_comment(repo: str, number: int, body: str, confirm: bool) -> None:
    if REPOSITORY_RE.fullmatch(repo) is None:
        sys.exit("invalid repository identifier")
    if not body.strip():
        sys.exit("refusing to post an empty comment")
    if not confirm:
        print(f"[dry-run] would post a comment ({len(body)} characters)")
        print("(re-run with --confirm to post)")
        return
    st, resp = _api("POST", f"/repos/{repo}/issues/{number}/comments", {"body": body})
    print(f"comment -> HTTP {st}")


def cmd_merge(repo: str, number: int, method: str, confirm: bool) -> None:
    if REPOSITORY_RE.fullmatch(repo) is None:
        sys.exit("invalid repository identifier")
    # re-check mergeability at the moment of merge (state can drift since triage)
    st, pr = _api("GET", f"/repos/{repo}/pulls/{number}", None)
    if st >= 300:
        sys.exit(f"could not load pull request: HTTP {st}")
    ms = pr.get("mergeable_state")
    if pr.get("draft"):
        sys.exit("refusing: pull request is a draft")
    if ms != "clean":
        sys.exit(f"refusing: mergeable_state={ms} (need 'clean')")
    if not confirm:
        print(f"[dry-run] would merge via {method}; mergeable_state=clean")
        print("(re-run with --confirm to merge)")
        return
    st, resp = _api(
        "PUT", f"/repos/{repo}/pulls/{number}/merge", {"merge_method": method}
    )
    print(f"merge -> HTTP {st}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("comment")
    c.add_argument("repo")
    c.add_argument("number", type=int)
    c.add_argument("--body", required=True)
    c.add_argument("--confirm", action="store_true")
    m = sub.add_parser("merge")
    m.add_argument("repo")
    m.add_argument("number", type=int)
    m.add_argument("--method", choices=["squash", "merge", "rebase"], default="squash")
    m.add_argument("--confirm", action="store_true")
    args = ap.parse_args()
    if args.cmd == "comment":
        cmd_comment(args.repo, args.number, args.body, args.confirm)
    else:
        cmd_merge(args.repo, args.number, args.method, args.confirm)


if __name__ == "__main__":
    main()
